name: HungerGames
version: Build#16
main: hungergames\Loader
author: xBeastMode
description: "The ultimate starvation game for minecraft pocket!"
api: [2.0.0, 1.13.0, 3.0.0, 3.0.0-ALPHA1, 3.0.0-ALPHA2, 3.0.0-ALPHA3]
load: STARTUP
permissions:
  hg.command.add:
    default: op
  hg.command.del:
      default: op
  hg.command.min:
      default: op
  hg.command.max:
      default: op
  hg.command.level:
      default: op
  hg.command.ws:
      default: op
  hg.command.gs:
      default: op
  hg.sign.create:
      default: op
  hg.command.slot.add:
      default: op
  hg.command.slot.del:
      default: op
  hg.command.lobby:
        default: op
  hg.command.dm:
        default: op
